[package]
name = "langcodec"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
indoc = "2.0.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
quick-xml = "0.37.5"
regex = "1.11.1"
unic-langid = "0.9.6"
