name: Rust
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache Rust builds
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Install langcodec-cli (prebuilt if available)
        run: cargo binstall -y langcodec-cli

      - name: Verify CLI
        run: |
          langcodec-cli --version

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
